---
version: '3.8'

services:
  amaui-rabbitmq:
    image: rabbitmq:management
    container_name: amaui-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=amaui
      - RABBITMQ_DEFAULT_PASS=amaui
    ports:
      - "5672:5672"
      - "15672:15672"

  amaui-rabbitmq-test:
    image: rabbitmq:management
    container_name: amaui-rabbitmq-test
    environment:
      - RABBITMQ_DEFAULT_USER=amaui
      - RABBITMQ_DEFAULT_PASS=amaui
    ports:
      - "7672:5672"
      - "17672:15672"
